project:
  type: website
  output-dir: .

website:
  title: "How hotel bookings differ based on the tourist's profile"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: true



