project:
  type: website
  output-dir: .

website:
  title: "How hotel bookings differ based on the tourist's profile"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: https://luis7ps.github.io/visualizacion-datos/pec3.html
        text: Volver

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: true



